project_id = "buildstart-selfhosted"

[functions.webhook-wsender-Glowix_books]
verify_jwt = false
[functions.process-message-Glowix_books]
verify_jwt = false
[functions.assetlinks-Glowix_books]
verify_jwt = false
[functions.broadcast-manager-Glowix_books]
verify_jwt = false
